### ISSUE TITLE
WinRT MIDI - Pointers captured in IAsyncOperations need to be validated

### ISSUE THREAD

**Issue by dingari** [juce-framework/JUCE#689] opened 2020-04-06 09:54 UTC
Hi, I've been experiencing crashes in my application and I stumbled upon a couple of places where raw `this` pointers are being captured in `IAsyncOperation` callbacks (see [WinRTInputWrapper](https://github.com/WeAreROLI/JUCE/blob/develop/modules/juce_audio_devices/native/juce_win32_Midi.cpp#L1583) and [OpenMidiPortThread](https://github.com/WeAreROLI/JUCE/blob/develop/modules/juce_audio_devices/native/juce_win32_Midi.cpp#L1446)). There are cases where the pointer may no longer be vaild when the callback is fired.

I've mitigated this problem in my code by wrapping the `this` pointer in a `WeakReference`, but I'm not sure that's sufficiently safe since the [docs](https://docs.juce.com/master/classWeakReference.html#details) mention that `WeakReference` on its own isn't thread-safe.

I'm happy to work on a fix if you can guide me in the right direction.

For reference, the code that was crashing is performing roughly these steps:

1. Scan the list of available MIDI outputs.
2. Find the corresponding MIDI input based on the output ID.
3. Attempt to open both input and output ports.
4. If either input or output can't be opened, close both ports.

It seems to be this immediate closing of the MIDI ports that can cause the lambda to be invoked after the `this` pointer becomes invalid.

**Comment by szarvas** [comment] 2022-09-27 18:05
Can you say if this issue still persists with the current JUCE version? I didn't have any luck reproducing it on my system.

Wrapping the `WinRTInputWrapper` in a WeakReference may be all right, since the `IMidiInPort` callback seems to happen on the message thread. The `OpenMidiPortThread` should probably use `shared_ptr` / `weak_ptr` to be thread safe.

**Comment by dingari** [comment] 2022-09-28 10:03
I can't say for sure since we've been maintaining our own JUCE fork internally with fixes and add-ons. I'd guess it would still be a problem since I don't see that the source has changed in the latest JUCE version.

Thinking back, I might have been opening/closing my MIDI devices on a separate thread at the time. If the `IMidiInPort` callbacks are happening on the message thread, you won't ever run into a race condition where `this` has been deleted from another thread. If you allow MIDI devices to be opened/closed on a separate thread, I'd think you need to make sure that the captured `this` is valid for the duration of the callback.

**Comment by dingari** [comment] 2022-09-28 10:22
Yep, looks like that was the case. Here's an excerpt from theproblematic code from that time:

```
class MyClass : private juce::MultiTimer,
                private juce::Thread,
                private juce::MidiInputCallback
{
    MyClass(juce::String in, juce::String out)
            : juce::Thread(in),
              state("STATE"),
              inputId(std::move(in)),
              outputId(std::move(out))
    {
        startThread();
    }

    ~MyClass() override
    {
        if (input)
            input->stop();

        stopThread(1000);
    }

    void MyClass::run() override
    {
        input  = MidiInput::openDevice(inputId, this);
        output = MidiOutput::openDevice(outputId);

        if (input && output)
        {
            setCurrentThreadName(output->getName());

            state.setProperty("id", output->getIdentifier(), nullptr);
            state.setProperty("device_name", output->getName(), nullptr);

            input->start();
            startTimer(TimerID::Timeout, TimeoutMs);

            state.addListener(this);

            // Initiate communication with device...
            // If successful, the timeout timer will be stopped in time.
        }
        else
        {
            if (!input)
                Logging::logMessage("Failed to open input: " + inputId);
            else
                Logging::logMessage("Failed to open output: " + outputId);

            handleTimeout();
        }
    }

    void timerCallback(int timerId) override
    {
        switch (timerId)
        {
            case TimerID::Timeout:
                Logging::logMessage("Timed out waiting for response from device: " + output->getName());

                handleTimeout();
                break;
                
            // Irrelevant timer cases omitted...

            default:
                break;
        }
    }

    void handleTimeout() override
    {
        stopTimer(TimerID::Timeout);

        input  = nullptr;
        output = nullptr;

        stopThread(1000);
    }

private:
    juce::ValueTree state;

    juce::String inputId, outputId;

    std::unique_ptr<juce::MidiInput>  input;
    std::unique_ptr<juce::MidiOutput> output;
};

```

**Comment by szarvas** [comment] 2022-09-28 17:12
Thanks for the excerpt, I gave it a good try.

Only because I had no luck reproing, and just to be sure: I can see you calling `handleTimeout()` --> `stopThread()` from inside `run()`, which in itself would be a threading issue. Maybe this just a mistake in this quick excerpt?

It's possible that I just don't have the kind of hardware MIDI devices that would trigger this problem, so we may wrap those raw pointers in some lifetime mechanism after all. It's just a bit annoying that we need to do this regardless of cancelling those async callbacks.

**Comment by dingari** [comment] 2022-09-29 09:42
Yeah, that may be a threading issue in and of itself, but a different one - I think. It's lifted directly from our source from two years ago, so it was a bug at the time!

We've since moved to a different approach for this class, which doesn't utilize a thread, so I can't say for sure. But the motivation for doing it this way at the time was that opening of MIDI devices through the WinRT libraries would sometimes block for a good few seconds if the devices aren't available for some reason - causing our UI to hang.

IIRC, it was more apparent with virtual MIDI ports or devices that only had an input/output, not both. But in any case this will be difficult to reproduce.

But looking at the JUCE source, we can't really be sure if the internals of `IMidiInPort` themselves are thread safe. What happens if a callback is already being fired (presumably on the main thread), and you cancel it from a different thread? It's an edge case for sure, and it doesn't look like anyone else has reported this issue for over two years.

You could just assert that construction/destruction of the MIDI device class happens on the message thread. Then this wouldn't really be an issue. And you wouldn't have the forced overhead of locking/checking the lifetime for every MIDI message received.

**Comment by szarvas** [comment] 2022-10-10 14:18
Commit https://github.com/juce-framework/JUCE/commit/fcb7e0fc20fd836323004c1c678fc98ff8e687ed on `develop` addresses this potential issue.

I will be closing the ticket shortly.

**Closed** 2022-12-19 14:13 UTC
