### ISSUE TITLE
[Bug]: OpenGL attachTo causes white flash

### ISSUE THREAD

**Issue by benkuper** [juce-framework/JUCE#1453] opened 2024-10-21 09:48 UTC
### Detailed steps on how to reproduce the bug

I have a main Open GL context that draws in a 1x1 pixel component and handle most part of the texture generation of my video mapping software.
Then I have different components that are sharing this main context with them using setNativeSharedContext. This already brings its complication, explained here #1452 

This issue is focused on the fact that those components are dockable / removable panels, meaning that I can add and remove then whenever I want. when a panel is created inside the main window, calling attachTo(*this) will cause a white flash before I have control over the rendering.

Interesting to note that those panel can also be floating, in which case they don't have a native titlebar and are transparent. In this case, the attachTo(*this) doens't flash white, but causes the whole panel to be invisible and then goes visible and rendering good.
This bug only appears when working in the main window.

Also interesting, this white flash is way more visible when assigning the software to my Nvidia 4080 GPU. When assigning it to my Intel integrated GPU, the white flashes are there but disappear way faster.

I believe this topic is related to it, but is from 2018 without a good outcome :
https://forum.juce.com/t/white-flash-for-the-first-opengl-frame-only-in-logic-pro/28240/17

### What is the expected behaviour?

No white flash

### Operating systems

Windows

### What versions of the operating systems?

11

### Architectures

64-bit

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment] 2024-10-22 18:43
> when a panel is created inside the main window, calling attachTo(*this) will cause a white flash before I have control over the rendering

Is the white flash just within the bounds of the component to which the GL context is attached, or does the entire window flash?

**Comment by benkuper** [comment] 2024-10-22 21:21
It is the the component bounds only.
Also, I tried putting some content in paintOverChildren() to see if it the flash would occur behind or in front, and the entire components flashes even if I'm drawing some stuff there.
I tried as well to put some flags and avoid drawing in renderGL before a certain time, but the flash still occurs (it seems that it's called before or during newContextCreated)

Right now, my workaround is to memorize the size of the component, set it to 1x1 pixel, then attach and then call with a delay a function that sets back the original size. i'm not happy with this but it's the closest to a decent UI that I can get right now.

**Comment by reuk** [comment] 2024-10-23 16:58
Thanks for reporting this issue. I can reproduce the issue in the DemoRunner when switching to an OpenGL demo, but only when the main renderer is set to Direct2D, rather than the software renderer.

To display OpenGL content on Windows, we create a secondary HWND to hold the OpenGL view, and then host this HWND inside the parent window, modifying the bounds of the secondary HWND so that they always match the bounds of the component to which the OpenGLContext is attached. It seems that when we first attempt to display this secondary HWND, it has no content because no frame has been rendered with OpenGL at that point. When using the software renderer, it seems that this unpainted window remains invisible until a frame is drawn by OpenGL. However, when the main window is painting with Direct2D, the area of the secondary HWND is displayed in white.

I'm not sure exactly where this difference in behaviour comes from, but my best guess is that the Direct2D implementation is 'smarter' than the software renderer, and avoids presenting areas of the window on-screen that it knows to be occluded by other windows.

It seems that we can avoid the white flash simply by waiting until a frame has been rendered with OpenGL before setting the secondary HWND to visible.

I've put together a patch that makes this change here: [0001-OpenGL-Avoid-displaying-OpenGL-window-until-a-frame-.patch](https://github.com/user-attachments/files/17495724/0001-OpenGL-Avoid-displaying-OpenGL-window-until-a-frame-.patch)

Please could you try applying that patch and see whether it solves the problem for you? Thanks!

**Comment by benkuper** [comment] 2024-10-23 18:06
thank you so much :)
tested and seems to work !
Because it was only flashing in the main window, does that mean my external windows are not rendered with Direct2D ? If that's the case, how do I set it to use D2D ? I'm creating a video mapping software, I'd like to have control over this kind of stuff :)

Thanks again, this can go into develop if you ask me ;)

**Comment by benkuper** [comment] 2024-10-23 18:12
So, tested with my setup and made sure to remove all the resize trick code, it doesn't flash indeed, but it doesn't show anything either.. :)

This is when the panel is inside the main window :
![image](https://github.com/user-attachments/assets/6adb71ba-c4b4-4632-9f3c-1bf34d5734c3)

And this is one it's detached :

![image](https://github.com/user-attachments/assets/dc1841a0-acd3-468c-9feb-6601ef790ee6)

**Comment by reuk** [comment] 2024-10-23 19:50
Please can you try out one of the JUCE OpenGL demos with that patch applied, maybe in the DemoRunner? The OpenGLDemo runs fine on my machine with the patch in place. If it doesn't work on your machine, then that might indicate that the fix isn't hardware-agnostic.

I also wonder if you're disabling continuous repainting for the GL component. If so, maybe nothing shows up because we're not forcing a repaint. That said, the OpenGLDemo2D (which doesn't paint continuously) seems to work fine here too.

**Comment by benkuper** [comment] 2024-10-23 19:51
My bad yes you're right, my software is the culprit, I actually have another panel even in this one where it works !
It's all good to go in develop for me :)

**Comment by reuk** [comment] 2024-10-23 19:54
Great, thanks for all of the prompt replies, that really helped! I'll get the changes ready for internal review, and I expect they'll be released in the next week or so if we don't find any new problems.

**Comment by reuk** [comment] 2024-10-24 20:28
Thanks for reporting, this should be fixed on develop: https://github.com/juce-framework/JUCE/commit/fcaf5adb25dde847dc1b2c7d90351ff36d05155b

**Closed by reuk** 2024-10-24 20:28 UTC
