### ISSUE TITLE
getAvailableDevices() in juce_mac_CameraDevice.h is incomplete  

### ISSUE THREAD

**Issue by leomccormack** [juce-framework/JUCE#651] opened 2020-01-03 13:27 UTC
1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code

File: juce_video/native/juce_mac_CameraDevice.h.  

Function: getAvailableDevices()   (line 239)

Since Apple's switch from Quicktime to AV (back in 2017), and the rewrite of this class, this function does not return the available camera devices. Rather, it only returns: "default". 

This issue can be clearly identified in lines 239-244, and shown in practice with the camera demo.

This has also been brought up previously here: https://forum.juce.com/t/webcam-support-incomplete-for-mac/24633/4

  2) the expected behaviour

It should return a list of the available camera devices, not just "default".

  3) the operating system

Only macOS. (juce_**mac**_CameraDevice.h)

  4) the architecture (32-bit or 64-bit)
  5) a stack trace - if the bug causes a crash
  6) the plugin format (VST2, VST3, AU, AAX, RTAS) - if applicable
  7) which DAW you observed the bug in - if applicable
n/a

**Comment by ed95** [comment] 2020-04-17 11:36
Duplicate of #587 which has now been closed.

**Closed by ed95** 2020-04-17 11:36 UTC
