### ISSUE TITLE
contribution guidelines

### ISSUE THREAD

**Issue by piem** [juce-framework/JUCE#555] opened 2019-07-11 14:06 UTC
@ed95 @julianstorer 

is there a way to submit patches without having them rewritten by someone else with no mention of the original author (see #548 and e206bbe)?

if copyright ownership is an issue, isn't it what a Contributor License Agreement is about? besides the fact that for such one-liner fixes, signing a CLA should not even be required.

README.md mentions contacting the authors, so here i go. I do have a few of such simple fixes for linux down the pipe.

cheers, Paul

**Comment by julianstorer** [comment] 2019-07-11 15:40
Hey Paul - yeah, we have a to-do-list item which is to publish a CLA and clear statement about contribution guidelines. 

The reasons we rewrite everything are:
a) It's very rare that anyone actually gets the style right (even for many of the one-liners, amazingly!)
b) The public repo is downstream from our private development repo, so we can't directly merge the pull requests - it has to be one of our team who commits them and runs it through CI
c) Regardless of CLAs, our lawyers prefer us to avoid having non-employees in the log, just to avoid unforeseen complications

If people commit bigger changes then we do confirm that they're OK to surrender the copyright, but for the really minor un-copyrightable stuff that would seem a bit silly. 

I can imagine that for some people, wanting to say they're a "juce contributor" by having their name in the log might be a valuable thing, but so far I think the motivation for most contributions has been that they needed the fix themselves, rather than expecting to be publicly credited for it.

**Comment by piem** [comment] 2019-07-11 16:05
hi @julianstorer 

thanks for your answers.

a) this is what PR comments are meant for. incidentally, in that case both patch and commit messages were unchanged.
b) `git` is built for this, and makes merging really trivial. with commands like `rebase` and `cherry-pick`, you can easily fetch commits from one branch to the other.
c) i assume this is the main argument, but it sounds like lack of knowledge. grabbing external contributions and pretend they were written by one of ROLI's employee does look more than sketchy to me.

There are automated hooks on github to ask first time contributors to sign a CLA. See how google's magenta is doing it for instance.

Recognition and fame are two different things. Saying «thank you» is always nice, and doesn't cost anything.

cheers, Paul

**Comment by christianscheuer** [comment] 2019-07-11 16:27
I have to say I agree with @piem here. I don't understand the lawyer argument. Having people sign a contribution agreement which as piem says can be fully automated on github, and is done that way by most major repos I contribute to, explicitly grants ROLI access - whereas copying people's contributions without asking them actually does the opposite and in my opinion runs a much higher risk legally. Why should ROLI be safer by doing this differently than everybody else?

To me the problem is that the continued closing and non-acceptance of PR's and responses like "we'll fix this soon" instead of accepting people's suggestions and interacting with them in a friendly and welcoming manner to teach them and/or change any styling problems (you can have PR's where project owners can make modifications, for example to fix styling issues), makes for a community where JUCE feels like a closed source product that you are not actually welcomed to contribute to. Seeing the responses to PR's in the past has kept me from ever wanting to submit anything. Just mentioning this since I think that's a shame that this awesome product is not welcoming more actual open source development.

**Comment by christianscheuer** [comment] 2019-07-11 16:33
See Microsoft's .NET repos for examples of keeping their internal codebase in sync with their open source repo. CLA are signed automatically for new users, very easily, granting explicit access to any contributions. Because their internal, closed source repos are synced with the open source ones, development is continuous and their attitude towards new contributors is to welcome them in, creating a feeling of making contributions is not only welcomed, but that you feel part of making something better.
I would love for JUCE to be able to choose a similar path. IMO there are no technical or legal issues that prohibits this (both a, b, and c can be mitigated and it allows for running much more real open, open source repos).

**Comment by julianstorer** [comment] 2019-07-11 17:01
Look, when we get chance to sort out a CLA, we can revisit these issues, but we're not going to get drawn into a rambling discussion about copyright here, as we can't comment without the approval of our legal counsel.

We DO thank and appreciate people who contribute fixes, but TBH I think that regardless of legal questions, there's a strong case to be made for JUCE keeping a heavy-handed approach to exactly what gets allowed in. I remember chatting to the creator of a similar-sized library which does rely on a huge amount of open-source contributions, but he said it was a bit of a double-edged sword because of the politics and people-management of the contributors - he needed their content, but had to be very sensitive about criticising or rewriting poorly-designed code because they'd get huffy about their work being changed.

For many years I refused to allow PRs at all - we only started responding to them because so many people asked to be able to use them as a way to show us the changes they wanted us to make!

**Comment by julianstorer** [comment] 2019-07-11 18:08
..and sorry but one last comment, as I want to clarify why it might seem I'm being a bit flippant about the value of contributors..

When you talk about "open-source contributors", it paints a picture of highly-motivated coders who choose an open-source project and put their free time into creating new features for it or making big improvements to it, maybe taking ownership of some aspect of the project, etc. The whole "bazaar" model. Linux kernel writers, etc.

But that's really nothing like the reality of the PRs we get for juce!

We (almost) never get PRs like "Implementation of big exciting new feature" or "Refactored and improved a set of fundamental classes that will benefit all juce users".

What we do get are things like "Fixed a typo because it was causing a bug in my app" or "Added a minor tweak to some existing class because I needed it, and thought maybe it'd be useful to a couple of other people too", or "Needed this minor change for my app, so can you guys please add it to the repo so it gets properly tested and maintained".

..and that's all great: we totally appreciate people reporting bugs and want to support the little tweaks that individual users need. Awesome. But in terms of time and effort, PRs are fairly neutral for us compared to a good bug report or FR. Even a one-liner PR need to be reviewed, thought about, tested, etc, which is a ton of work. And many one-liners really do need re-writing, or trigger other bits of related refactoring.

For example, look at the change that kicked off this whole thread - why even send a PR? A quick message saying "hey guys, that number should be "96" like it says in the comment above" would have been just as easy for Ed to handle - he still had to review it, find an appropriate linux machine, build and test it, commit it, run it through CI. And if it hadn't been a PR, we wouldn't all have got sucked into this ensuing thread about copyrights and credit!

**Comment by piem** [comment] 2019-07-11 19:05
Hmm. Maybe you could just close PRs then. Or just the entire code base as well while at it.

When I propose a patch for inclusion in a tree, I test it thoroughly, check the coding style matches the one of the project, test it again, check the way the log messages should be written, write it, and sign the commit with my key.

When I receive a PR, I expect the same from whoever submitted it, and I also spend time to review and test the patches. But I would not even think about complaining that I'm loosing time because some user tried and made an effort to contribute to the project. Even if I do.

This thread is not really about changing the value of a constant. As I mentioned earlier, I have more patches to submit, but if there is no interest on your side, I'll just keep them private.

**Comment by julianstorer** [comment] 2019-07-11 20:40
> When I propose a patch for inclusion in a tree, I test it thoroughly, check the coding style matches the one of the project, test it again, check the way the log messages should be written, write it, and sign the commit with my key.

I've no doubt you do! But without wanting to throw shade at the many people who've submitted JUCE PRs, in our experience that amount of diligence is... unusual.. Obviously there's a core group of people we know and trust, but the number of PRs we get where they've not even bothered to make a single line of code match the style of the one next to it is depressingly high!

> But I would not even think about complaining that I'm loosing time because some user tried and made an effort to contribute to the project. Even if I do.

Nobody's complaining - like I said multiple times, we welcome and appreciate any contributions that people want to send us. We just find that keeping a layer of insulation between the incoming requests and our codebase is a system that works well for us, that's all. Sorry if that offends you in some way.

**Comment by piem** [comment] 2019-07-11 22:03
No offense, but certainly a bit of frustration, and apparently I'm not alone. Looking forward to reading updates from the legal side, which seems to be the real obstacle here. In the mean time, I'll keep sending PRs, as long as they are open.

**Comment by dromer** [comment] 2021-09-18 22:31
Seeing the amount of trivial copy/paste commits that are happening from genuine contributors .. is there any update in this legal/CLA stuff?

This is not rocket science yet is quite demotivating developers, especially for minor fixes that are just "rebranded" by JUCE devs.
Having more strict guidelines for features and larger PRs makes sense of course, but even those can easily be worked out with a little bit of sane git usage.

For all the trivial stuff it would be a lot easier for everybody (yes for JUCE devs as well) if some simple CLA was in place so that fixes can be merged much more easily and efficiently.

**Comment by omartijn** [comment] 2022-02-07 11:56
Looks like there is some CLA-check now, but it doesn't work, because the page it links to doesn't actually display any kind of license. It just shows a white rectangle where the license should be.

**Comment by dromer** [comment] 2022-02-07 12:19
@omartijn did you go to https://cla.juce.com/ and went through the steps to verify your GH account?

**Comment by omartijn** [comment] 2022-02-07 12:24
Yes, that's where I went. That site asks me to review the "JUCE Contribution Licence Agreement", which it then does _not_ show.

![image](https://user-images.githubusercontent.com/44672243/152787627-817a6a46-ba2d-4f94-b6f1-add0a77a0f5f.png)

**Comment by dromer** [comment] 2022-02-07 12:41
Check your browser, it should load a PDF.

**Comment by tpoole** [comment] 2022-02-08 11:48
What browser are you using? Are you using any extensions that might block an embedded PDF?

**Closed** 2022-03-02 16:39 UTC
