### ISSUE TITLE
[Bug]: (JUCE 8) fileComponentThatHasChanged callback doesn't include the updated value

### ISSUE THREAD

**Issue by BOBONA** [juce-framework/JUCE#1402] opened 2024-06-23 10:26 UTC
### Detailed steps on how to reproduce the bug

In JUCE 7, I was able to add a listener to the FilenameComponent and do an action on the new filename with fileComponentThatHasChanged->getCurrentFile(). In JUCE 8, this does not fetch the newly selected file, which seems to undermine the point of the method.

### What is the expected behaviour?

I'd expect to be able to see the newly selected file.

### Operating systems

Windows

### What versions of the operating systems?

Windows 11

### Architectures

x86_64, 64-bit

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment] 2024-06-24 19:12
So far I've been unable to reproduce this issue. The CodeEditorDemo correctly displays the content of the file selected using the FilenameComponent.

- Do you see the same problem in any of the JUCE examples, such as the CodeEditorDemo?
- How are you interacting with the FilenameComponent: typing in a new name, clicking on the ellipsis button to open a browser, or using the dropdown menu to select a file?
- Does the text of the FilenameComponent update correctly to reflect the most recently picked file?
- Are you using native or non-native file-choosers?

If you're able to demonstrate the bug in one of the JUCE examples or in a small code snippet, that would help us to track down the issue.

**Comment by BOBONA** [comment] 2024-06-24 19:43
It seems to be something more complicated with my code, and now the behavior seems to be inconsistent... The issue only began when I updated, so I'll investigate and hopefully find something concrete.

**Comment by reuk** [comment] 2024-06-27 11:11
It sounds like the issue is somewhere else, and is not necessarily in JUCE code, so I'm going to close this issue. If you determine that the issue you're seeing was caused by a bug/regression in JUCE, please open a new issue.

**Closed by reuk** 2024-06-27 11:11 UTC
