### ISSUE TITLE
AudioUnit view loading logic might be incorrect

### ISSUE THREAD

**Issue by adamnemecek** [juce-framework/JUCE#1001] opened 2022-01-20 19:06 UTC
I was investigating some crash and came across this code

https://github.com/juce-framework/JUCE/blob/master/modules/juce_audio_processors/format_types/juce_AudioUnitPluginFormat.mm#L2317

It seems that if you are on macOS and you are loading a auv3 plugin, you are still trying to load the view as if it were a auv2 plugin and only then loading it as if it were a v3 plugin. It should only be loading the view once.

**Comment by reuk** [comment] 2022-01-21 14:28
What was the crash? Does this crash with a specifc plugin? If so, please let us know which plugin crashes so that we can reproduce the issue locally.

**Comment by reuk** [comment] 2022-01-26 22:35
I'm unable to reproduce the issue in the AudioPluginHost or in Tracktion Engine demos, so I'm closing this issue for now.

**Closed by reuk** 2022-01-26 22:35 UTC
