### ISSUE TITLE
[Bug]: Raspberry Pi broken Graphics since 7.0.3 (tested on 64-bit)

### ISSUE THREAD

**Issue by benkuper** [juce-framework/JUCE#1159] opened 2022-12-06 11:10 UTC
### Detailed steps on how to reproduce the bug

Install fresh raspbian 64-bit on raspberry 4
clone JUCE 
make
launch Projucer

The window is buggy

Additional notes :

I’ve been compiling on CI for raspberry many times without problems, and I just discovered that one of my apps is having troubles rendering the main window on raspberry.
Strangely, I have another app that works just fine.
I decided to compile it directly from the Raspberry, starting with the Projucer, and I discovered that the Projucer itself is having the exact same problem

![image](https://user-images.githubusercontent.com/1291595/205895819-a801df0c-209a-4a70-af0c-2c77b500a125.png)

I’ll try to summarize my findings, you can try the bleeding edge version to see the problem

OS = Raspbian Bullseye 64-bit
JUEC : Fork synchronized to latest commit of develop branch (slightly modified but no big UI changes)
App1 = Chataigne ( [Chataigne | Chataigne 1](https://benjamin.kuperberg.fr/chataigne) )
App2 = LGML ( [LGML | Le Grand Mechant Loop](https://benjamin.kuperberg.fr/lgml) )

Normal GUI Mode (not using OpenGL Renderer) :
App1 = Works
App2 = Does not work (screenshot above)
Projucer = Does not work (screenshot above)

OpenGL renderer mode :
App1 = Works
App2 = Works but not really : the app shows quite alright but the menubar is showing the same bug
Projucer = Not tested with GL renderer

App1 & App2 are both using the same sub-framework for generating the UI ( OrganicUI : [GitHub - benkuper/juce_organicui: A massive JUCE module that adds multiple UI and control features 1](https://github.com/benkuper/juce_organicui) ) which allows to switch between renderers.

It’s quite reassuring that Projucer is having the same problem but then I don’t know why App1 is actually working…

If you have any idea about that I’m all ears !
Thank you

### What is the expected behaviour?

The GUI is showing normally

### Operating systems

Linux, Other

### What versions of the operating systems?

Raspbian OS 64-bit
JUCE 7.0.3 (latest develop branch)

### Architectures

ARM, 64-bit

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by benkuper** [comment] 2022-12-06 20:52
Small update on that : 
the new version of App1 (Chataigne) doesn't work anymore, the latest working is 1.9.12b2, and I updated JUCE in between b2 and b3.
b2 was synced on master 7.0.2
b3 is synced on latest develop, which is few commits ahead of 7.0.3

I suspect some commits around September 26/27th changing OpenGL's handling, but I don't have more informations.

**Comment by reuk** [comment] 2022-12-07 14:52
At the moment I'm not able to reproduce this issue. I'm using 64-bit Raspberry Pi OS (bullseye), fully-updated, on a Raspberry Pi 4. I've tried building the Projucer in debug and release, and both configurations seem to work as expected.

**Comment by benkuper** [comment] 2022-12-07 15:08
Interesting..
The only thing I've changed from the stock Raspberry is updating the kernel for a PREEMPT Realtime, but I wouldn't think it comes from that... ?

**Comment by reuk** [comment] 2022-12-07 15:54
When I connect using remote desktop, the Projucer window does fail to repaint properly. I'll investigate further.

**Comment by benkuper** [comment] 2022-12-07 15:55
ah yes sorry I totally forgot to mention I was using VNC..

**Comment by reuk** [comment] 2022-12-07 17:05
Please could you check whether this change resolves the issue for you?

```diff
From 187c5e087320c39a65b4dbdcf75a9e52a267ed0d Mon Sep 17 00:00:00 2001
From: reuk <reuk@users.noreply.github.com>
Date: Wed, 7 Dec 2022 17:00:02 +0000
Subject: [PATCH] XWindowSystem:  Default to standard refresh rate if the real
 refresh rate is unavailable

---
 modules/juce_gui_basics/native/juce_linux_Windowing.cpp | 9 +++------
 1 file changed, 3 insertions(+), 6 deletions(-)

diff --git a/modules/juce_gui_basics/native/juce_linux_Windowing.cpp b/modules/juce_gui_basics/native/juce_linux_Windowing.cpp
index 29d702f4f6..e18bd4e660 100644
--- a/modules/juce_gui_basics/native/juce_linux_Windowing.cpp
+++ b/modules/juce_gui_basics/native/juce_linux_Windowing.cpp
@@ -571,13 +571,10 @@ private:
     {
         if (auto* display = Desktop::getInstance().getDisplays().getDisplayForRect (bounds))
         {
-            if (display->verticalFrequencyHz)
-            {
-                const auto newIntFrequencyHz = roundToInt (*display->verticalFrequencyHz);
+            const auto newIntFrequencyHz = roundToInt (display->verticalFrequencyHz.value_or (100.0));
 
-                if (vBlankManager.getTimerInterval() != newIntFrequencyHz)
-                    vBlankManager.startTimerHz (newIntFrequencyHz);
-            }
+            if (vBlankManager.getTimerInterval() != newIntFrequencyHz)
+                vBlankManager.startTimerHz (newIntFrequencyHz);
         }
     }
 
-- 
2.38.1
```

**Comment by benkuper** [comment] 2022-12-07 18:34
Thanks !
Sent to CI, will test when it's compiled

**Comment by benkuper** [comment] 2022-12-07 21:22
Nope, problem's still there..

**Comment by benkuper** [comment] 2022-12-08 17:38
So indeed the commit you mention is the faulty one, but the fix doesn't fix it on my side...

**Comment by benkuper** [comment] 2022-12-08 18:04
Ok I think I got it, I debugged a bit around the patch lines, and it seems that 
```
auto newIntFrequencyHz = roundToInt (display->verticalFrequencyHz.value_or (100.0));
```` 
returns 0 (I guess the display->verticalFrequencyHz actually has a value but it's 0)

I added a simple
```
if(newIntFrequencyHz == 0) newIntFrequencyHz = 100;
```

just after, to force a non-zero value and it works just fine !

**Comment by reuk** [comment] 2022-12-08 18:15
OK, thanks for that. I'll get that merged.

**Comment by benkuper** [comment] 2022-12-08 19:47
Thanks for the quick handling !

**Comment by reuk** [comment] 2022-12-14 17:08
Thanks for reporting, this is now fixed on develop: https://github.com/juce-framework/JUCE/commit/676e10fdd9e9641a258963f6b62003911005e656

**Closed by reuk** 2022-12-14 17:08 UTC
