### ISSUE TITLE
VST3 support on Linux

### ISSUE THREAD

**Issue by 0joshuaolson1** [juce-framework/JUCE#307] opened 2017-11-19 20:45 UTC
As of now [juce_CheckSettingMacros.h](https://github.com/WeAreROLI/JUCE/blob/develop/modules/juce_audio_plugin_client/utility/juce_CheckSettingMacros.h) shows that it's exclusive to Windows and macOS:
```
#if ! (defined (_MSC_VER) || defined (__APPLE_CPP__) || defined (__APPLE_CC__))
 #undef JucePlugin_Build_VST3
```

**Comment by 0joshuaolson1** [comment] 2018-11-29 01:12
I see this is still the case. Why is that?

**Comment by atsushieno** [comment] 2019-04-02 19:09
This also seems to be the cause of defect where Bitwig Studio wins over Waveform. I'm exploring other DAWs than Waveform because of lack of VST3 support. VST3 is the only available choice for VST product developers anymore, and lack of this means DAWs without VST3 support is dead end.

**Comment by fpesari** [comment] 2019-07-23 16:26
It seems that the VST3 SDK is now under the GPLv3 ([repo](https://github.com/steinbergmedia/vst3sdk)), I hope this will be an incentive to support it since [Steinberg stopped supporting it](https://www.steinberg.net/en/newsandevents/news/newsdetail/article/vst-2-coming-to-an-end-4727.html)

**Comment by flyingrub** [comment] 2019-08-01 10:15
Can we have more infos on why it is not actually supported ?

**Comment by ed95** [comment] 2019-08-01 10:27
It's in development but requires a significant amount of work to JUCE's underlying Linux backend. It will be released in the future, but we are wary of giving firm date estimates for things like this.

**Comment by ed95** [comment] 2020-04-17 11:39
This has been added to the `juce6` preview branch in commit [de712ca](https://github.com/juce-framework/JUCE/commit/de712ca02e2bca8a7b66e1f4c99ff246dd6a7c47).

**Closed by ed95** 2020-04-17 11:39 UTC
