### ISSUE TITLE
Unusually high CPU usage in (empty) JUCE OpenGL application

### ISSUE THREAD

**Issue by Intrets** [juce-framework/JUCE#945] opened 2021-08-29 17:41 UTC
When playing around with JUCE and OpenGL I noticed my program was doing essentially nothing but showed high CPU usage. Trying from a fresh and latest version of JUCE, an empty project created from projucer or the demo apps showed the same high CPU usage.

**System**:
OS: Windows 10 home build 19043
CPU: Ryzen 3700x
GPU: GTX 1660 super, driver 471.68
Visual Studio: 16.11.2

**Reproducing steps**:
1. Download windows release from [https://github.com/juce-framework/JUCE/releases/tag/6.1.0](https://) (at time of testing and writing, the release is up to date with develop/master branches)
2. Unzip to a folder `$Foo`, run Projucer, File -> Global Paths -> set Path to JUCE to `$Foo/JUCE`, set JUCE modules to `$Foo/JUCE/modules`
3. Create new project -> OpenGL
3. Open project in Visual Studio 2019
4. Build and run the standalone executable (either Debug and Release will exhibit the CPU usage)

**Expected result:**
Very minimal CPU usage by the application.

**Actual result:**
The application completely saturates one core and then some.
This shows in task manager, the Visual Studio profiler, and while breaking the program with the debugger at an arbitrary time the execution of the program is guaranteed to be in the same function.

**Comment by Intrets** [comment] 2021-08-29 20:46
OK so this has to do with the graphics driver blocking when swapping buffers and apparently that can pop up in any call, but it is freakishly consistent in which one it is... really confusing and completely threw me off.

Taking a look at how GLFW handles this: [https://github.com/glfw/glfw/blob/63da04e5ced93fcb87a20513acdff5d78b1166ff/src/wgl_context.c#L321-L342](https://github.com/glfw/glfw/blob/63da04e5ced93fcb87a20513acdff5d78b1166ff/src/wgl_context.c#L321-L342), seems to be a good solution even though it is called a hack.

**Comment by SamuelBeland** [comment] 2021-10-08 15:52
@Intrets

Try switching off continuous repainting with `OpenGLContext::setContinuousRepainting(bool)`.

Continuous repainting will always saturate the rendering thread, either by doing actual work or just by sleeping (so that it doesn't hog the _Message Manager_ by constantly locking it).

See the body of `juce::OpenGLContext::CachedImage::renderFrame()`

```cpp
// ...

// This avoids hogging the message thread when doing intensive rendering.
if (lastMMLockReleaseTime + 1 >= Time::getMillisecondCounter())
    Thread::sleep (2);

// ...
```

**Comment by jjYBdx4IL** [comment] 2022-04-13 15:04
The problem is that the GL context is released after every frame. This is a VERY expensive operation on Windows (WGL). The context should be acquired once at the start of the render thread loop, and released at the end. Currently, it puts one CPU core to its limit on a Ryzen 5600x´without doing anything than clearing the screen.

Also: swap interval doesn't work that way it seems. It's always at 60 fps for me.

Also: MSI Afterburner OSD (free app for live gfx card performance introspection) makes the plugin crash. I have this problem nowhere else.

Please fix. It's really easy. Just keep the rendering on the same thread.

**Comment by jjYBdx4IL** [comment] 2022-04-14 04:07
My debugger tells me that this takes around 100ms to execute:

https://github.com/juce-framework/JUCE/blob/master/modules/juce_opengl/opengl/juce_OpenGLContext.cpp#L351

> OpenGLContext::deactivateCurrentContext();

wgl

**Comment by jjYBdx4IL** [comment] 2022-04-14 05:29
If I use a timer instead of continuous repaint, and set the timer to the same fps (60 Hz), I get 1/30 of the CPU usage with the same frame rate. When I set the timer to 260 fps, I still get only 60 fps, but the CPU core is at its limit.....?

**Comment by jjYBdx4IL** [comment] 2022-04-14 06:05
I could make a pull request for this if desired.

**Comment by tpoole** [comment] 2024-11-20 14:58
We believe this is fixed in JUCE 8. Please re-open this issue if you are still seeing problems.

**Closed by tpoole** 2024-11-20 14:58 UTC
